server.servlet.context-path=/equaled
#spring.datasource.url=jdbc:mysql://${DB_IP}:3306/equaled
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://${PG_DB_IP}/equaled
spring.datasource.username=${PG_DB_USERNAME}
spring.datasource.password=${PG_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
#hornetq.port=5445
cors.origins=*
server.port=8082

logging.level.com.equaled = trace

management.endpoints.web.exposure.include=loggers,health
spring.jackson.default-property-inclusion=non_null


amazonProperties.endpointUrl=https://curious-campus.s3.eu-west-2.amazonaws.com
amazonProperties.bucketName=curious-campus
amazonProperties.accessKey=AKIAWNHTHSOUFFSIOUMN
amazonProperties.secretKey=${AWS_SECRET}

spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=48MB
spring.servlet.multipart.enabled=true
